# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

# Given that this file is specific to Windows, we check for the existence of
# the "tcl_platform(debug)" variable and load only the debug versions of DLLs.
# This ensures that we do not inadvertently load release DLLs (e.g., DLLs
# without the "d" tag) when running a Tcl shell built for debugging (e.g.,
# "protclsh82d.exe").

# Packages should be loaded from the win32-ix86/bin directory, the
# pkgIndex file is in the win32-ix86/lib directory to be consistent
# with Unix.  Load ../bin/xxx.dll.

if {[info exists tcl_platform(debug)]} {
    set _dbgx "d"
} else {
    set _dbgx ""
}

# dde and reg are auto loaded from their own pkgIndex.tcl files

package ifneeded tbcload  1.3 [list load [file join $dir ../bin tbcload13${_dbgx}.dll] tbcload]
package ifneeded Itcl     3.2 [list load [file join $dir ../bin itcl32${_dbgx}.dll] Itcl]
package ifneeded Itk      3.2 [list load [file join $dir ../bin itk32${_dbgx}.dll] Itk]
package ifneeded Tclx     8.3 [list load [file join $dir ../bin tclx83${_dbgx}.dll] Tclx]
package ifneeded Tkx      8.3 [list load [file join $dir ../bin tkx83${_dbgx}.dll] Tkx]

unset _dbgx
